### ISSUE TITLE
can't start listen

### ISSUE THREAD

**Issue by rampageX** [cherrot/gochinadns#12]
Linux asus 2.6.36.4brcmarm #1 SMP PREEMPT Wed Dec 19 07:47:43 CET 2018 armv7l GNU/Linux

> $ ./chinadns -p 54 -v
> INFO[0000] 193.112.15.186:2323: average RTT 9.900583ms with 0 errors.
> INFO[0000] 119.29.29.29:53: average RTT 37.194065ms with 0 errors.
> INFO[0000] 114.114.114.114:53: average RTT 33.271687ms with 0 errors.
> INFO[0000] Refined trusted resolvers: [193.112.15.186:2323]
> INFO[0000] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
> INFO[0000] Start server at [::]:54
> panic: listen udp 0.0.0.0:54: protocol not available
> 
> goroutine 1 [running]:
> main.main()
> 
> $ ./chinadns -p 5053 -v
> INFO[0000] 193.112.15.186:2323: average RTT 9.752631ms with 0 errors.
> INFO[0000] 119.29.29.29:53: average RTT 36.254511ms with 0 errors.
> INFO[0000] 114.114.114.114:53: average RTT 33.997863ms with 0 errors.
> INFO[0000] Refined trusted resolvers: [193.112.15.186:2323]
> INFO[0000] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
> INFO[0000] Start server at [::]:5053
> panic: listen tcp 0.0.0.0:5053: protocol not available
> 
> goroutine 1 [running]:
> main.main()
> 	/mnt/data/compile/go/src/github.com/cherrot/gochinadns/cmd/chinadns/main.go:119 +0x704

**Comment by cherrot** [comment]
Is your router running OpenWRT?  If so, please paste your OpenWRT version here.

It seems that your router doesn't allow an UDP binding, which is abnormal.

**Comment by cherrot** [comment]
Sorry I can't reproduce your issue on my devices.

Could you help me to test its TCP binding? To do so, just comment out the following line and re-build to see if this issue remains:

https://github.com/cherrot/gochinadns/blob/44e1301f2958adbc0364afad239992279adb8e87/server.go#L68

Like this:
> ```
> func (s *Server) Run() error {
> 	logrus.Info("Start server at ", s.Listen)
> 	eg, _ := errgroup.WithContext(context.Background())
> 	// comment out the following line.
> 	// eg.Go(s.UDPServer.ListenAndServe)
> 	eg.Go(s.TCPServer.ListenAndServe)
> 	return eg.Wait()
> }
> ```

**Comment by rampageX** [comment]
I run [Tomato](https://www.linksysinfo.org/index.php?threads/fork-freshtomato-arm.74117/unread) on ASUS RT-AC68P. I commented UDP/TCP one by one, results:

##Comment UDP:

```
./chinadns -p 5053 -v
INFO[0000] 193.112.15.186:2323: average RTT 9.451211ms with 0 errors.
INFO[0000] 119.29.29.29:53: average RTT 36.101136ms with 0 errors.
INFO[0000] 114.114.114.114:53: average RTT 32.890729ms with 0 errors.
INFO[0000] Refined trusted resolvers: [193.112.15.186:2323]
INFO[0000] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
INFO[0000] Start server at [::]:5053
panic: listen tcp 0.0.0.0:5053: protocol not available

goroutine 1 [running]:
main.main()
	/mnt/data/compile/go/src/github.com/cherrot/gochinadns/cmd/chinadns/main.go:119 +0x704
```

##Comment TCP:

```
./chinadns -p 5053 -v
INFO[0000] 193.112.15.186:2323: average RTT 9.01861ms with 0 errors.
INFO[0000] 119.29.29.29:53: average RTT 35.875695ms with 0 errors.
INFO[0000] 114.114.114.114:53: average RTT 33.276077ms with 0 errors.
INFO[0000] Refined trusted resolvers: [193.112.15.186:2323]
INFO[0000] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
INFO[0000] Start server at [::]:5053
panic: listen udp 0.0.0.0:5053: protocol not available

goroutine 1 [running]:
main.main()
	/mnt/data/compile/go/src/github.com/cherrot/gochinadns/cmd/chinadns/main.go:119 +0x704
```
The golang app [overture](https://github.com/shawn1m/overture) worked well on my router, so maybe i can say this is not a hardware/system issue?

##overture:

```
netstat -lnp | grep overture
tcp        0      0 0.0.0.0:5554            0.0.0.0:*               LISTEN      1078/overture
tcp        0      0 :::8054                 :::*                    LISTEN      1078/overture
udp        0      0 0.0.0.0:5554            0.0.0.0:*                           1078/overture
```

**Comment by cherrot** [comment]
I'll check it later. Thank you for reporting :)

**Comment by cherrot** [comment]
We rely on the same upstream dns lib. So I guess the reason is that your router does not support IPv6 dual-stack. 

Try this:
```shell
./chinadns -b 0.0.0.0 -p 5053 -c ./china.list -v
```

**Comment by cherrot** [comment]
Or maybe it's because I've enabled SO_REUSEPORT by default (This feature is supported since Linux 
 3.9). 

I'll make it configurable soon.

**Comment by rampageX** [comment]
Yes, I disable IPv6 on my router, but other apps running smooth~ I tried `-b`, some result:

```
./chinadns -b 0.0.0.0 -p 5053 -c ./china.list -v
INFO[0000] 193.112.15.186:2323: average RTT 44.653103ms with 0 errors.
INFO[0000] 119.29.29.29:53: average RTT 36.551825ms with 0 errors.
INFO[0001] 114.114.114.114:53: average RTT 34.308061ms with 0 errors.
INFO[0001] Refined trusted resolvers: [193.112.15.186:2323]
INFO[0001] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
INFO[0001] Start server at 0.0.0.0:5053
panic: listen udp 0.0.0.0:5053: protocol not available

goroutine 1 [running]:
main.main()


./chinadns -b 127.0.0.1 -p 5053 -c ./china.list -v
INFO[0000] 193.112.15.186:2323: average RTT 9.250139ms with 0 errors.
INFO[0000] 119.29.29.29:53: average RTT 36.169572ms with 0 errors.
INFO[0000] 114.114.114.114:53: average RTT 33.403527ms with 0 errors.
INFO[0000] Refined trusted resolvers: [193.112.15.186:2323]
INFO[0000] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
INFO[0000] Start server at 127.0.0.1:5053
panic: listen udp 127.0.0.1:5053: protocol not available

goroutine 1 [running]:
main.main()


./chinadns -b 192.168.2.1 -p 5053 -c ./china.list -v
INFO[0000] 193.112.15.186:2323: average RTT 9.3855ms with 0 errors.
INFO[0000] 119.29.29.29:53: average RTT 36.411543ms with 0 errors.
INFO[0000] 114.114.114.114:53: average RTT 32.918727ms with 0 errors.
INFO[0000] Refined trusted resolvers: [193.112.15.186:2323]
INFO[0000] Refined untrusted resolvers: [114.114.114.114:53 119.29.29.29:53]
INFO[0000] Start server at 192.168.2.1:5053
panic: listen udp 192.168.2.1:5053: protocol not available

goroutine 1 [running]:
main.main()
	/mnt/data/compile/go/src/github.com/cherrot/gochinadns/cmd/chinadns/main.go:119 +0x704
```
I think you are right! SO_REUSEPORT is the key, because the router running linux 2.6....

**Comment by cherrot** [comment]
```shell
./chinadns -p 5053 -c ./china.list -v -reuse-port=0
```
Good luck!
